// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ContactFormPopupController from "./contact_form_popup_controller"
application.register("contact-form-popup", ContactFormPopupController)

import CursorController from "./cursor_controller"
application.register("cursor", CursorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
